services:
  my-database:
    image: mysql:8.0.31
    container_name: test-db
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: "%"

  server:
    depends_on:
      - my-database
    stdin_open: true
    tty: true
    container_name: test-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src:ro

volumes:
  mysql-volume:
